name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t abdullah2222/nodejs-app .
      - name: Publish image to docker hub
        run: docker push abdullah2222/nodejs-app:latest

  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull abdullah2222/nodejs-app
      - name: Delete old container
        run: sudo docker rm -f nodejs-app-container
      - name: Run docker container
        run: sudo docker run -d -p 5000:5000 --name nodejs-app-container abdullah2222/nodejs-app